### ISSUE TITLE
Pycodestyle heavily failing

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#105]
@ladinesa @ndaelman-hu , the pipeline is failing with a lot of fails regarding pycodestyle in some parsers. Should this be fixed?

**Comment by ladinesa** [comment]
This is the very reason why I always remind running pylint and pycodestyle locally. Not sure who will take this over. Maybe look at the list of errors and if you think you are responsible please commit the necessary fixes.

**Comment by ndaelman-hu** [comment]
Will solving this make the pipeline pass? If so, we should look into this, else this can come later imo.

**Comment by JosePizarro3** [comment]
> This is the very reason why I always remind running pylint and pycodestyle locally.

That's why I created the label 😆 

> Will solving this make the pipeline pass? If so, we should look into this, else this can come later imo.

Nope, but at least we should be reaching pylint, without pycodestyle errors, right?

**Comment by ndaelman-hu** [comment]
> Nope, but at least we should be reaching pylint, without pycodestyle errors, right?

Sure, but it's very low-priority. I can take it, but next week at the earliest.

@ladinesa Any update on the other tests? When could we start implementing them again?

**Comment by ladinesa** [comment]
> Will solving this make the pipeline pass? If so, we should look into this, else this can come later imo.

The thing is, we are updating the metainfo quite frequently and the nomad release cannot keep up. I will update the nomad lab package in the github workflow but this may not necessarily make the tests pass if the metainfo defs version is not update to date. 

Again, please run pylint, pycodestyle and pylint locally. It is harder to fix when these errors add up.

**Comment by ladinesa** [comment]
> 

I think addressing pylint and pycode should not be secondary. @ndaelman-hu not sure what you mean update on the other tests. If you mean, when the pylint will pass in github tests and run the tests, I do not think this will ever happen because as I have said we are updating nomad frequently and releases are not done every update. We discussed this months ago and I have warned you of this exact situation.

**Comment by JosePizarro3** [comment]
Maybe a very dumb question: is it possible to skip pylint in the github actions? Or skip it + include a message saying "Please run pylint locally with: ....."?

Seeing that we are never going to be able to pass that part of the pipeline, maybe we should do it like this?

**Comment by ladinesa** [comment]
> Maybe a very dumb question: is it possible to skip pylint in the github actions? Or skip it + include a message saying "Please run pylint locally with: ....."?
> 
> Seeing that we are never going to be able to pass that part of the pipeline, maybe we should do it like this?

The tests will not run because you are using an outdated nomad package.

**Comment by ndaelman-hu** [comment]
@ladinesa Yes, these are the tests that I meant. I mostly remember there being a problem with a package, that's why I was asking.

I understand your point regarding the metainfo though. Do you think that the NOMAD installation could be automated?
On Gitlab, the CI/CD produces a docker image, maybe Github could pull it? Just an idea.

> I think addressing pylint and pycode should not be secondary.

No, I get you, but it's fine if we fix it next week, right? I think we're all oversaturated with other tasks atm.

**Comment by ladinesa** [comment]
Actually, you can manually trigger release for your commit, but I think you should ask Markus if you can do this. It is not part of the commit workflow because we do not want to clutter the nomad releases.

**Comment by ladinesa** [comment]
I managed to fix the issues and also the github workflow. The develop branch should always pass now.

**Comment by ndaelman-hu** [comment]
So, the current develop has no linting errors? Many thx!

**Comment by ndaelman-hu** [comment]
@ladinesa Could you please bump up the _pylint_ version? Currently, it's at `2.3.0`, which [has a bug in it with `Union`](https://github.com/pylint-dev/pylint/issues/3882). This is making me [fail the pipeline](https://github.com/nomad-coe/electronic-parsers/pull/107/commits/777d9f0ede6712381992d2ad9583586d2a17857c). [The minimally required version is `2.6.1`](https://pypi.org/project/pylint/#history), but I'd prefer the same one as on Gitlab.

**Comment by ndaelman-hu** [comment]
@ladinesa Could you please bump up the _pylint_ version? Currently, it's at `2.3.0`, which [has a bug in it with `Union`](https://github.com/pylint-dev/pylint/issues/3882). This is making me [fail the pipeline](https://github.com/nomad-coe/electronic-parsers/pull/107/commits/777d9f0ede6712381992d2ad9583586d2a17857c). [The minimally required version is `2.6.1`](https://pypi.org/project/pylint/#history), but I'd prefer the same one as on Gitlab.

**Comment by ndaelman-hu** [comment]
Moreover, could we pls also swap the order of the tests to that in Gitlab? i.e.

1. pytest
2. pycodestyle
3. mypy
4. pylint

Out of these, `pytest` is the most informative of all. Meanwhile, fixing the linting it something that one can do at the very end, before merging. `pylint`, on the other hand, is the slowest of all the linting tests, so it can go last.

**Comment by ladinesa** [comment]
I updated pylint  and added directive to always run pytest. You can always run theses tests locally if you need quick feedback.

**Comment by ndaelman-hu** [comment]
Many thx!
