### ISSUE TITLE
w2dynamics test failing

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#136]
@ladinesa , @lauri-codes pointed out that the `test_w2dynamics.py` is failing after my last merge. The part failing is the last one about asserting the Fermi energy (it happens locally too):

```
 >       assert sec_scf[0].energy.fermi.to('eV').magnitude == approx(14.15922513307991)
E       AttributeError: 'NoneType' object has no attribute 'fermi'
```

Strangely, I was debugging with VSCode to this file, and I can retrieve the value as in the test. When uploading the file to the local nomad installation, I can see:

![Screenshot from 2023-07-20 13-08-42](https://github.com/nomad-coe/electronic-parsers/assets/112697669/65190347-f6e9-446b-a204-915bea24e43f)

I can deactivate the test, but if you have any ideas why, I can try to implement the fix.

**Comment by ladinesa** [comment]
I can have a look later today. do you know if this was working when it was still skipped?

**Comment by ladinesa** [comment]
I think the reason is archive is missing m_context. For local tests to pass, you should put the assignment of the energy fermi out of the loop since it does not use the context for the hdf storage..

**Comment by JosePizarro3** [comment]
Ok, I can leave the tests out. Thanks a lot for pointing this out.
