### ISSUE TITLE
Bug on parsing GeometryOptimization in CP2K

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#140]
When investigating to add [PDOS to CP2K](https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/1605), I realized there is some bug with the GeomOpt parsing. It seems the refs to system are not properly parsed.

@ladinesa do you want to take care of this? I can pass you some files for testing. Otherwise, I will do it but it is not an urgent priority (I prefer to fix the SinglePoint parsing).

**Comment by ladinesa** [comment]
I can have a look. please attach files.

**Comment by JosePizarro3** [comment]
> I can have a look. please attach files.

Sure, let me fix first the SinglePoint part in a soon-to-be-push merge. Thanks!

**Comment by JosePizarro3** [comment]
@ladinesa I am reopening this issue, as it seems that the `SinglePoint` is buggy. I tried the 10-ring data from Andrea, and it cannot parse the system, thought it should be a very easy task.

[10_rings_island_42h.zip](https://github.com/nomad-coe/electronic-parsers/files/12358122/10_rings_island_42h.zip)

Can you tell me what might be happening?

**Comment by ladinesa** [comment]
> @ladinesa I am reopening this issue, as it seems that the `SinglePoint` is buggy. I tried the 10-ring data from Andrea, and it cannot parse the system, thought it should be a very easy task.
> 
> [10_rings_island_42h.zip](https://github.com/nomad-coe/electronic-parsers/files/12358122/10_rings_island_42h.zip)
> 
> Can you tell me what might be happening?

ok i can have a look after our meeting.

**Comment by ladinesa** [comment]
It seems that it is able to create a system for the initial structure. For the trajectory, the traj file is missing. Is this the error that you encounter?

**Comment by JosePizarro3** [comment]
Yes, you are right. I saw you discussed this with Andrea. Then it is a mater of him adding some extra files so system can be recognized. Otherwise, the DOS normalization will break.
