### ISSUE TITLE
Update parser tests for new thermostat metainfo

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/electronic-parsers#167]
fix FHIaims, check other tests

**Comment by JosePizarro3** [comment]
Hi @JFRudzinski, I see the `test_fhiaimsparser.py` is failing. This has a very easy fix, as `thermostat_parameters` is a list, so line 259 should point to the [0] element.

Or are you planning other changes?

**Comment by JFRudzinski** [comment]
@JosePizarro3 Yes exactly. Would you mind making the change? I was planning to do it during the week. I did not anticipate how busy I would be but I have not had a second to breath 😮‍💨

**Comment by JosePizarro3** [comment]
Sure, I'll quick fix it in #166 .
