### ISSUE TITLE
FHIaims extra Method section

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#18]
The FHIaims parser incorrectly parses the method sections and add an extra one with references plus only `electronic.method='DFT'`. You can see it in all `single_point` entries in the beta repo.

This happens at the end of `parse_configurations:parse_section`, where an if is screwing up the parsing (at least this is what I think, but further investigation is needed). @ndaelman-hu agreed to have a look.

One small point: I think this issue should be solved **after** the GW branch is merged. In that case, the lines where this happen are 1300-1305ish. Otherwise we can overwrite each others work.

**Comment by JosePizarro3** [comment]
Btw, I can help you review the mods as these should be only at the parser level.

**Comment by ndaelman-hu** [comment]
Please let me know when #17 is merged, then I'll start this up.

**Comment by JosePizarro3** [comment]
Ok @ndaelman-hu , the GW branch was merged, so you can check this out.

Let me know when you need my help or review.

**Comment by JosePizarro3** [comment]
Hi @ndaelman-hu ,

This bug is propagating a little bit. I am making some minimal changes to the `MethodNormalizer` and it seems I cannot proper get the DFT method section because of the wrong parsing.

I edit comenting that KMesh seems to be parsed to run.method[1], i.e. into the dummy Method section? Not sure if I understand what's going on.

Can you please take a look and let me know when it is push? I can quickly review it.

**Comment by JosePizarro3** [comment]
Maybe @ladinesa should be also tagged here, as I can see from one of the tests (`test_fhiaimsparser.py:test_geomopt`):

```
def test_geomopt(parser):
    archive = EntryArchive()
    parser.parse('tests/data/fhiaims/Si_geomopt/out.out', archive, None)

    sec_methods = archive.run[0].method
    # one more since 0 is core settings
    assert len(sec_methods) == 7
```

**Comment by ndaelman-hu** [comment]
So indeed, the lines
```
            if self._calculation_type == 'dft':
                sec_method = sec_run.m_create(Method)
                sec_scc.method_ref = sec_run.method[-1]
                sec_method.electronic = Electronic(method='DFT')
                sec_method.core_method_ref = sec_run.method[0]
                sec_method.methods_ref = [sec_run.method[0]]
```
are responsible for adding this appendix.
They're easy enough to remove, but I have the feeling that they are trying to convey an additional step. I'll ask around a bit.

**Comment by ndaelman-hu** [comment]
Btw, it also appears that our FHIaims parser cannot properly capture geometry optimizations: https://nomad-lab.eu/prod/v1/staging/gui/search/entries/entry/id/zx5lCPkb-ueoXPRq8zy88szxtRcU/data/workflow/single_point

**Comment by JosePizarro3** [comment]
I see, then it is a matter of deleting those lines. 

Please, don't forget to include `sec_scc.method_ref` at the beginning of `parse_section` and modify the tests accordingly. 

@ladinesa do you agree? I think the FHIaims parser got outdated, and it might be affecting other parts. For example, now I am wondering whether `MethodNormalizer` has these lines for number_of_method>1 because of this. If we all agree, @ndaelman-hu you patch this up, and then I keep working on https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/merge_requests/1078 to clean up the `MethodNormalizer`.

Thanks!

**Comment by ladinesa** [comment]
i am not sure which part is outdated but if you make changes both in nomad or in the parser please make sure to run the tests before merging.

**Comment by JosePizarro3** [comment]
> i am not sure which part is outdated but if you make changes both in nomad or in the parser please make sure to run the tests before merging.

indeed @ndaelman-hu , the tests_fhiaimsparser fails for the geometry optimization if you delete those lines. But I'd say the test should be updated anyways.

**Comment by ndaelman-hu** [comment]
So, I pushed the changes to `18-fhiaims-extra-method-section`. The geometry calculation fails since it states to have the no. steps + 1. Obviously, there should only be a single method.

Am putting up a PR now.
