### ISSUE TITLE
Corrupted elements in VASP

### ISSUE THREAD

**Issue by ndaelman-hu** [nomad-coe/electronic-parsers#187]
It has been found that `vasprun.xml` incorrectly prints` <c>r </c>`, instead of `<c>Zr</c>`.
This has been found for `vasp.5.4.4.18Apr17-6-g9f103f2a35`, though the extent of this formatting error is as yet unknown.

The big question is: should we be able to cope with this error? The answer will depend on the size of this formatting error.

**Comment by ndaelman-hu** [comment]
@ladinesa Would like your opinion here.

For an example of the corrupted data, I refer to @schumannj

**Comment by ladinesa** [comment]
I am not sure how rhe parsing would fail. I have to run it myself.

**Comment by schumannj** [comment]
sorry @ladinesa, seems not to be a general problem with vasp, rather a typo in one of the POTCARs, that translated into the vasprun file

**Comment by ndaelman-hu** [comment]
Fun fact: the vasprun.xml uses the `VRHFIN` tag in the POTCAR.
Not sure yet how OUTCAR does it, but it seems way more robust.
