### ISSUE TITLE
problematic frequency parsing from Gaussian files

### ISSUE THREAD

**Issue by schumannj** [nomad-coe/electronic-parsers#229]
I have 2 Gaussian files with frequency calcualtions, but the frequencies are not parsed correctly. in x_gaussian_section_frequncies the x_gaussian_frequency vector lists all frequencies twice and has some empty rows. Can you fix this?
See [here for the link to the data.](https://nomad-lab.eu/prod/v1/gui/user/uploads/upload/id/XenO4Le6QyOHXHBpdxtVgA/entry/id/UhX9zipy_CbGau7pOe23rlNgy4Fo/data/run/0) It is shared with @ndaelman-hu and @ladinesa . Let me know if you need something else.

**Comment by JosePizarro3** [comment]
Are these Raman calculations? Sorry, I cannot access the information on the link. 

If so, I would suggest the following, depending on your deadline @schumannj: we will transfer the Gaussian to its own plugin, and then take care of defining a `RamanSpectra` property with the [new Simulations schema](https://github.com/nomad-coe/nomad-simulations). This will have the advantage that you will not need to use these quantities `x_gaussian...`, but they will rather be quantities properly found under `data.outputs.raman_spectra`.

If you need it to be fixed asap, we can take a look on the parser and do a quick patch.

@ladinesa what do you think of this? Do you prefer to fix this asap and later transfer Gaussian anyways to a plugin?

**Comment by ladinesa** [comment]
I would also put up a fix in the old schema unless @ndaelman-hu  would llike to take over?

**Comment by ndaelman-hu** [comment]
Update: found the reason.

Gaussian prints the vibrational section 2x (not sure yet why).
However, some quantities, e.g. reduced mass and normal modes are denoted slightly differently. The main difference is the normal mode notation.

Our parser cannot handle the first output format, though the Gaussian schema did distinguish between these 2 headers and sections. I've removed this now

**Comment by ndaelman-hu** [comment]
@schumannj We aren't extracting the (harmonic) force constants nor the IR intensities. Do you need these?

**Comment by schumannj** [comment]
That would be great, thank you!

**Comment by ndaelman-hu** [comment]
@schumannj have added IR intensities and Harmonic force constants.

**Comment by ndaelman-hu** [comment]
closed with #232 
@schumannj you can update parser version in the main

**Comment by ndaelman-hu** [comment]
Found a small error with the unit conversion that had some Gaussian tests fail (hard to tell from the verbose list with warnings). Will patch this quickly.

**Comment by ndaelman-hu** [comment]
Patched
