### ISSUE TITLE
Erroneous mapping from E(min) to E Fermi

### ISSUE THREAD

**Issue by ndaelman-hu** [nomad-coe/electronic-parsers#3]
In `test_vaspparser.py/test_outcar()` the Fermi energy stored in `sec_scc.energy.fermi` or `sec_dos_energy_fermi` does not match the Fermi energy in raw data file (`DOSCAR` = 5.87176757 eV).
Instead, it stores the lower energy range of the DOS (-31.70651295 eV).
Both values are on the same line in positions 4 and 2, respectively.

**Comment by ndaelman-hu** [comment]
This bug is caused by a change in output format of FHIaims, e.g.:
- version 082212 `| Chemical potential (Fermi level) in eV                 : -.78743505E+01`
- version 190715, 201231, 210618, 210716.1, 220619 `| Chemical potential (Fermi level):    -4.57977802 eV`

Note that the order of the units (eV) and values swaps, meaning that the groups mappings also change.
Hence, we cannot redesign the regex to a more general case, but have to use different ones.

From discussing with @JosePizarro3, should we extend `nomad/parsing/file_parser/text_parser.py/Quantity` to support multiple regexes (matching certain versions)?
Maybe it is worth if we find other such cases.

**Comment by JosePizarro3** [comment]
Should we close this issue, as it was solved with our new regex?
