### ISSUE TITLE
Workflows for advanced many-body methods

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#31]
Hi @ladinesa ,

I was working these days on the GW (and more generally in any advance method like Projections or DMFT) workflows. The idea is that there is not extra entries associated with comparisons.

I think we could achieve this by storing the single point and the GW in the same workflow (as elements on the list `gw_archive.workflow`). A second step will be to delete the single point element (`del gw_archive.workflow[0]`). 

I was playing with this idea and it seems to be working. I can push some changes for you to check it out.

What do you think? I think there are a few gains by doing it so (please, let me know if there is any drawback, as I cannot inmediately see it), namely no extra entries and GW vs DFT comparison directly on the GW entry, which is what users will be looking for.

**Comment by ladinesa** [comment]
The idea of the overall workflow for gw is more consistent with the other workflow types. Take an elastic constant calculation for example. The values for the elastic constant are saved in the workflow. For gw, the comparison should not be saved in the gw single point entry but in the workflow. With this, I really believe that the single point gw calculation should be a separate entry from the gw workflow that includes both the basis calc and the gw calc.  Also, the new workflow section is non repeating which means we cannot push more than one workflow in an entry. We should discuss this more in detail with Luca befoee peoceeding.

**Comment by JosePizarro3** [comment]
Ok, I understand the argument; a small clarification: when I said delete the extra entry, I meant that the GW entry (whether is "single point" or "GW workflow") should contain the comparison with DFT already. 

I think the comparison being a separate entry inside a "GW workflow" is a bit cumbersome, and might be a bit misleading: e.g., some people might wanna be looking at energies at different k-meshes for (GW) convergence studies, hence they will be looking for a "GW workflow", while the individual GW entries should still contain the comparison.

We can discuss with Luca next year :-)

**Comment by JosePizarro3** [comment]
I then close this issue (and the corresponding branch and pull request) after our latest discussion with Luca, @ladinesa 

We keep then the advanced many-body methods workflow as the comparison + probably some extra quantities plots.
