### ISSUE TITLE
Incorrect parsing of the cutoff energy in vasp_parser

### ISSUE THREAD

**Issue by qhassanzada** [nomad-coe/electronic-parsers#5]
The parser checks the PREC, and if it is acc (accurate), the value of ENCUT is multiplied by 1.3. According to the VASP wiki for [PREC] (https://www.vasp.at/wiki/index.php/PREC), if the PREC is high, the value of ENCUT would be ~ 1.3 times ENMAX. Furthermore, If the PREC is set to high (and ENCUT is not specified by the user), the VASP performs this multiplication itself, and it would give a wrong value if this is again done by the parser.

For example in the calculation below which is for the monoclinic structure of Ga2O3: the PREC is high (ENCUT is not set) and the ENCUT and ENMAX values are modified by VASP automatically (ENCUT in OUTCAR and ENMAX in vasp.xml). 
[Ga2O3_without-encut_prec-high.zip](https://github.com/nomad-coe/electronic-parsers/files/9375219/Ga2O3_without-encut_prec-high.zip)

**Comment by ndaelman-hu** [comment]
This seems to occur because of line 1160 of electronicparsers/vasp/parser.py (commit a1b7948)  `prec = 1.3 if 'acc' in self.parser.incar.get('PREC', '') else 1.0`.

Before ammending anything, @qhassanzada could you make a list of VASP versions where this happens?

**Comment by qhassanzada** [comment]
I have checked this issue for three different versions of VASP which I have access to them (5.4.1, 5.4.4, 6.1). The files are attached to this issue. 

[vasp_test2.zip](https://github.com/nomad-coe/electronic-parsers/files/10279914/vasp_test2.zip)

I found that in all of them when the PREC is high (not accurate) and ENCUT is not specified by the user then the ENCUT automatically is multiplied by 1.3 by VASP and we should avoid doing that again in the parser, otherwise extracted value for the ENCUT would be wrong.  

I have solved this issue in VASP parser and checked it within the test_vaspparser.py by using pytest. The extracted ENCUT value is the same as the value from the output.

**Comment by ndaelman-hu** [comment]
@ladinesa Could you pls add @qhassanzada to the contributors list?

**Comment by ndaelman-hu** [comment]
So, one thing that @qhassanzada told me, is that the use of `ENMAX` and `ENCUT` is somewhat vague (see the uploaded examples).
`ENMAX` is set in _POTCAR_, and read as such by the _OUTCAR_. The final cut-off is denoted in `ENCUT`.
Meanwhile, vasprun.xml does not report the _POTCAR_ headers, just the cut-off, as `ENMAX`.

So, clearly the semantics between the files is confusing. Atm, @qhassanzada resolved this extracting `ENCUT`, with a fallback onto `ENMAX`. This is quite an elegant solution, but obfuscates what's being corrected for. Alternatively, we could extract the cutoff differently in the OUTCAR and vasprun.xml parsers.
@ladinesa Which do you prefer?

**Comment by ladinesa** [comment]
not sure if i really understood the problem but personally we should save these parameters as they are ENCUT or ENMAX as they are parsed. in incar_out, not renaming them. for the calculation of the planewave_cutoff, we should simply put an additional if statement in the calculation of the factor prec to correct for multiplying twice if prec is high and no ENCUT in incar_in.

**Comment by ndaelman-hu** [comment]
Okay, thank you for your insight. In that case, that would coincide with the current implementation.
Once @qhassanzada has added some tests, we'll push a Merge Request.

**Comment by ndaelman-hu** [comment]
Solved along with the pseudopotentials
