### ISSUE TITLE
vasp total energy is wrong when uploading OUTCAR

### ISSUE THREAD

**Issue by mdforti** [nomad-coe/electronic-parsers#50]
when uploading OUTCAR file to nomad, run.calculation.energy.{total, free, total_T0}  are wrong.

**Comment by mdforti** [comment]
I followed the issue up to https://github.com/nomad-coe/electronic-parsers/commit/bab48a9579cfd5a125cf4e11446937fade83eb8d but everything seems fine in the prints. 

However, when uoloading the file, it seems to be assigning some other value

**Comment by ladinesa** [comment]
can you please perhaps forward me the file/

**Comment by mdforti** [comment]
you can see upload Bk0z-gfNRN2XuelJwRr8tg ?

**Comment by ladinesa** [comment]
I looked into it and it appears that we multiplied the total energy by the number of atoms. In other versions, the printed energy in OUTCAR is the energy per atom but in this case, it is the total energy. I will have to survey all vasp versions to see exactly what is actually printed and make the necessary correction. Thank you for reporting this very important bug.

**Comment by ladinesa** [comment]
It seems that all version indeed print the total energy not per atom so I have put up a fix to develop. It will update the parser ref in nomad corresponding later.

**Comment by mdforti** [comment]
It gave me that impression but did not spot the actual moment when the number of atoms is multiplied.

**Comment by ladinesa** [comment]
shall we close this now?

**Comment by mdforti** [comment]
if already implemented, go ahead

**Comment by mdforti** [comment]
how many uploads are there with this error ?

**Comment by ladinesa** [comment]
i am really not sure but OUTCAR is the secondary mainfile for vasp vasprun.xml takes priority. We are doing a reprocessing in a couple of months so all uploads will be corrected.

**Comment by mdforti** [comment]
How can I use this fix ?  

For local parsing using the python interface, I can cherry  pick the commit over the head of the freshly installed submodule but when pulling the nomad repo and  initiating the submodules again the fix is lost. 

The fix is also not implemented in nomad web page, as the problem persists there also.

**Comment by ladinesa** [comment]
it should already be integrated with nomad beta as far as I can see.

**Comment by mdforti** [comment]
true! although the material card seems to be broken there. check for example upload ID auYu1h5XTCy8XaZxo3KXLw .  Also, how do I configure my oasis to pull the beta version ?

**Comment by markus1978** [comment]
Using the `latest` tag will give you the latest release, using the `develop` tag will give you everything that is already merged. The beta is usually somewhere in between.

**Comment by ladinesa** [comment]
I willl have a look at your upload and will let you know.

**Comment by mdforti** [comment]
dont know what you did guys but the material card is now shown correctly.

**Comment by mdforti** [comment]
a fresh pull of my oasis works well. Thanks !
