### ISSUE TITLE
Wien2k calculations don't show method name DFT

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/electronic-parsers#51]
See for example 
https://nomad-lab.eu/prod/v1/gui/search/entries/entry/id/NHp0k9nwRi-RuOKPQmxG9A/E3uubwm0J7xcxbqZHOqKuV2FDOal

**Comment by JosePizarro3** [comment]
Hi Pavel, 
I cannot access this data. Is it belonging to a specific upload you have or is it publish?

**Comment by ondracka** [comment]
Strange, the link I provided is not my upload but some test Wien2k upload by Markus Scheidgen (I can see it in v1 repo even when loged out)

Some of my uploads with the same issue are for example here:  https://nomad-lab.eu/prod/v1/gui/search/entries/entry/id/t9V-EraoTBKMFWbjRLvUHA/x7aIY5RPy5WqeLi2g4aC4Wb4zLmz or https://nomad-lab.eu/prod/v1/gui/search/entries/entry/id/X78d1GK-QJGbpM9y0sgY2w/bejOG-fYEaF53kHC-8PS5dfmkvYK

Every other DFT program I looked at in NOMAD (VASP, Quantum Espresso, Exciting, OpenMX, etc...) shows the method name DFT properly in the web GUI. The Wien2k parser does set  https://github.com/nomad-coe/electronic-parsers/blob/1e81425636f8178bd404a296fe69513fc20f8fd9/electronicparsers/wien2k/parser.py#L689
however maybe it needs also `sec_method.electronic = Electronic(method='DFT')` or something? I don't have a full Oasis set up locally right now, so its not easy for me to check how backend changes propagate to web GUI otherwise I would send a patch...

**Comment by JosePizarro3** [comment]
I cannot see the uploads, but I think I understand the issue.

Indeed, for resolving the `method_name='DFT'`, this is ran in `nomad/nomad/normalizing/method.py` in the main nomad Gitlab. It is set by checking whether `run.method.electronic` **AND** `run.method.electronic.method='DFT'` exist, so there is the problem (don't ask me why it needs this, as me myself don't fully get it :smile: ).

I can patch it quick and push the changes. It is just about having these lines in the Wien2k parser: 
```
        sec_dft = sec_method.m_create(DFT)
        sec_electronic = sec_method.m_create(Electronic)
        sec_electronic.method = 'DFT' 
```

**Comment by ondracka** [comment]
Thanks for the quick fix.
