### ISSUE TITLE
molecular dynamics support for fhiaims

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/electronic-parsers#57]
Initiated by @lauri-codes: 
"A former colleague of mine is doing ab-initio MD with FHIaims. He has several example outputs and was asking if it makes sense to upload such files to NOMAD. I tried one of these but the parser is not handling them very well. I think that all of the frames are captured correctly, but none of the MD methodology or trajectory energies etc. are captured.

There is actually already an MD test file in the repo: https://github.com/nomad-coe/electronic-parsers/blob/develop/tests/data/fhiaims/HO_md/H2O_periodic_MD.out, and a test is defined for this file in https://github.com/nomad-coe/electronic-parsers/blob/develop/tests/test_fhiaimsparser.py. The python file is just lacking the proper tests for what would be expected from an MD run."

**Comment by JosePizarro3** [comment]
@JFRudzinski can you keep me on the loop for this? I will be happy to help with the FHIaims parser.

You can name me reviewer of the pull request in the future.

**Comment by JFRudzinski** [comment]
@JosePizarro3 : Yes, definitely! That was indeed my plan. I am still working on initial changes atm, but I will keep you updated.
