### ISSUE TITLE
VASP parser does not recognise XC functional

### ISSUE THREAD

**Issue by markus1978** [nomad-coe/electronic-parsers#66]
In this dataset the XC functional has not been recognised for the majority of entries: https://dx.doi.org/10.17172/NOMAD/2017.03.15-1

**Comment by JosePizarro3** [comment]
It seems that in the INCAR, GGA is set to ML, and this key is not implemented in the `xc_functional_mapping` in the VASP parser. This is contemplated in the [VASP wiki for GGA](https://www.vasp.at/wiki/index.php/GGA).

I think @ndaelman-hu should take a look anyways, as I am not an expert as he is on the XC functionals.

**Comment by ndaelman-hu** [comment]
I agree with @JosePizarro3 's assessment (btw, thx for tagging me).
The main question is not capturing it, but where to map it to: the composing X and C functionals are in our LibXC standard, though here they are using a reparametrized version of X, which isn't.
I'll also have a look into the libVdwXC, since they are updating a vdw-DF2, which is anyhow outside the scope of LibXC.

All the more reason to step away from these standards, as they don't cover everything and change themselves over time, though for the time being I'll patch this.

**Comment by JosePizarro3** [comment]
I see. In that case you are totally right, and really doubt that we should give support to this.

What about an alternative tag for the XC functionals which allows to identify these cases clearly as `reparametrized` (indistinctively of which part of XC and for how much)?

**Comment by ndaelman-hu** [comment]
I would start by **adding citations to the original papers**, along with a native (libxc / libxcvdw and code-specific) tag.
The main purpose of the latter is to have a common way of searching for the functionals, but in and of themselves they don't mean much.

**I like your suggestion of `reparametrized`.** It applies to many functionals, but I can trace this now with my _DFT knowledge graph_. The main point with reparametriztion though is to also capture the benchmark: data set or physical constraint.

These are obviously extensive additions, so **for the time being I will give it a label base on libvdwxc**.
@markus1978 @ladinesa This functional metadata shouldn't be set by the parsers, but actually not even by the normalizes. Based on the native tag, I can set all other metadata. **If this is shown to the user in a dynamic way, then updating this metadata wouldn't require reparsing and would take effect immediately.** What do you think?

**Comment by lucamghi** [comment]
Assuming that the base X is in libxc, I fully agree we need a boolean `reparametrized` , which should be *searchable*.
Without waiting to have libVdwXC knowledge-graphed with refs, actual capture of changed parameters, and so on, do we admit its list of functionals as possible values for xc functional? 
We need that the list is closed but not restricted (life is made of trades offs)

**Comment by ndaelman-hu** [comment]
So, this XC functional is captured as **vdW-DF2 in libvdwxc** (10.1088/1361-651X/aa7320), and I would map it into **VDW_X_DF2** and **VDW_C_DF2**, which are tags that we already have.
(Note: VDW_C_DF2 = VDW_C_DF and I will remove the former.)
I'll also update the description to reflect that we use libxc , as well as libvdwxc.

The `reparametrization` tag is something that I'll add in the future.
Moreover, just saying that it is reparametrized misses the main point of this density functional: it has a non-local correlation, which is outside the scope of libxc.
It is not libxc X_reparametrized + C, but rather a reparametrization of vdw-DF1 (namely its X), which isn't in libxc either. I should've been clearer here, sorry.

**Comment by lucamghi** [comment]
Ok, fine for now.
For the `reparametrized` tag, I am wondering if the fact that the xc is not standard (i.e., in no library we adopt or even in no publication) is something the input/output always signals clearly. Worst case scenario is a tampered code with cryptic indication (some hash telling that the build is not a std version). Just saying... there is no limite on what people do when developing a project and then they are not strongly motivated to communicate FAIRly what they have done.

**Comment by ndaelman-hu** [comment]
Well, this case is still quite standard (I would consider libvdwxc an extension of libxc + the functional was published), but I get your concern. As long as the references are clearly communicated, I can decide on the distinction and see to communicate the semantics as best possible (like in this case).
When the citation is left out, we should reach out to the developers. At some point, we could invite them to give feedback to our functional description.

**Comment by lucamghi** [comment]
I agree. The main concern, tho, is that one gets a warning when an xc is modified. I always think it is better to get a false negative (an XC is not recognized but infact it was a standard one, some bug in the parser and/or code communication) than a false positive (an XC is stored as one of the standard while it isn't)

**Comment by ndaelman-hu** [comment]
@lucamghi Actually, there is an example of what you mentioned in VASP: [RSCANL](https://www.vasp.at/wiki/index.php/METAGGA). It follows the same prinicple as SCANL and R2SCANL, but there is no publication of it. Just an invention from the VASP team. The change here is the usage of the kinetic energy density for the density laplacian.

**Comment by lucamghi** [comment]
Well, but at least it gets a different name, so, as long as we can distinguish it is good. The impact of the change can be discovered only projecting onto a curated benchmark dataset... but this will come (much) later, if ever.
