### ISSUE TITLE
Broken ABINIT test

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#73]
@ladinesa for some reason that I didn't discover, the pytesting for ABINIT is broken.

This does not happen if the tests are ran individually with `pytest tests/test_abinitparser.py -k '.....'`.

Am I overlooking something?

**Comment by ladinesa** [comment]
You should reinitialize the private variables when reusing the parser. I put up a fix.

**Comment by ladinesa** [comment]
can you verify if fixed and then close it?

**Comment by JosePizarro3** [comment]
It works, thanks a lot and sorry for not reinitializen dataset_numbers.
