### ISSUE TITLE
TBS parser

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/electronic-parsers#90]
Hi @mohammadnakhaee , 

I created the skeleton of the parser in the branch `tbs_parser`. From here, you can define / populate your sections / quantities. Here I would like to stress again a couple of things:

- The difference between code-specific from general metainfo. For the code specific, you can always extend sections using `tbs/metainfo/tbs.py`. You can follow the conventions used in other parsers as an example, but the general idea is to define code-specific quantities with `x_codename_...`, hence in your case you could have `x_tbs_...`.
- Whenever you have any doubt, feel free to come to my office and we can check it together.
- Also drop docstrings whenever you can so we have a good maintainance of the parser on the long term :slightly_smiling_face: 

As you see, right now this branch is pointing to `1008-plugin-mechanism` as I branched out from it, but later we will have to rebase to `develop`. 

I will also include the MatchingParserInterface in the gitlab branch, so you understand where does it come from.

Once we finish an initial version, we pass it to Alvin for a final check.

**Comment by JosePizarro3** [comment]
I can change the naming, no worries. You can focus on having the sections populated, which is already all the work :D

**Comment by JosePizarro3** [comment]
Ok, done, also please: at the end of developing the parser, do not forget to include some testing for the populated sections in `tests/test_tbstudio.py` and `tests/data/tbstudio/`.

**Comment by JosePizarro3** [comment]
@mohammadnakhaee You have to open a PR here too in order to see changes (just saying, in case you didn't know 🙂 ). If it is already on your agenda, no worries, I will wait as much as you want.

**Comment by mohammadnakhaee** [comment]
Yes I still nedd time to finish some small things
